domains:

- staging.julieandjeremyareawesome.com
- www.julieandjeremyareawesome.com

routes:

  /:

    controller: page
    name: home
    properties:
      view: /views/base.html
      content: /content/home.yaml

  /public/<grow:basename>:

    controller: static
    name: static
    properties:
      view: /public/:basename

  /<grow:slug>/:

    controller: page
    name: page
    properties:
      view: /views/base.html
      content: /content/:slug.yaml
